###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.7"
services:

    webserver:
      image: nginx:alpine
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"
      depends_on:
       - php-fpm

    php-fpm:
      build: phpdocker/php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
      depends_on:
        - mysql

    mysql:
      image: mysql:5.7
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=123456
        - MYSQL_DATABASE=admin_course
        - MYSQL_USER=admin_course
        - MYSQL_PASSWORD=pp6321

    myadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            TZ: Asia/Bangkok
            PMA_HOST: mysql
        ports:
            - 8001:80
        links: 
            - mysql
    

